# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_RPS.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    class creates a window for GUI
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(660, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(29, 20, 581, 31))
        self.Title.setObjectName("Title")
        self.LowerTitleLine = QtWidgets.QLabel(self.centralwidget)
        self.LowerTitleLine.setGeometry(QtCore.QRect(23, 45, 611, 16))
        self.LowerTitleLine.setObjectName("LowerTitleLine")
        self.UpperTitleLine = QtWidgets.QLabel(self.centralwidget)
        self.UpperTitleLine.setGeometry(QtCore.QRect(23, 5, 611, 16))
        self.UpperTitleLine.setObjectName("UpperTitleLine")

        self.round_result = QtWidgets.QLabel(self.centralwidget)
        self.round_result.setGeometry(QtCore.QRect(30, 180, 551, 51))
        self.round_result.setObjectName("round_result")

        self.radioRock = QtWidgets.QRadioButton(self.centralwidget)
        self.radioRock.setGeometry(QtCore.QRect(50, 320, 121, 41))
        self.radioRock.setObjectName("radioRock")

        self.radioPaper = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPaper.setGeometry(QtCore.QRect(250, 320, 121, 41))
        self.radioPaper.setObjectName("radioPaper")

        self.radioScissors = QtWidgets.QRadioButton(self.centralwidget)
        self.radioScissors.setGeometry(QtCore.QRect(450, 320, 211, 41))
        self.radioScissors.setObjectName("radioScissors")

        self.Choose = QtWidgets.QPushButton(self.centralwidget)
        self.Choose.setGeometry(QtCore.QRect(225, 440, 181, 41))
        self.Choose.setObjectName("Choose")
        self.Play_Again = QtWidgets.QPushButton(self.centralwidget)
        self.Play_Again.setGeometry(QtCore.QRect(84, 440, 181, 41))
        self.Play_Again.setObjectName("Play_Again")
        self.Quit = QtWidgets.QPushButton(self.centralwidget)
        self.Quit.setGeometry(QtCore.QRect(360, 440, 181, 41))
        self.Quit.setObjectName("Quit")

        self.choose_hand = QtWidgets.QLabel(self.centralwidget)
        self.choose_hand.setGeometry(QtCore.QRect(30, 260, 400, 41))
        self.choose_hand.setObjectName("choose_hand")

        self.user_score_disply = QtWidgets.QLabel(self.centralwidget)
        self.user_score_disply.setGeometry(QtCore.QRect(30, 80, 531, 51))
        self.user_score_disply.setObjectName("user_score")
        self.computer_score_disply = QtWidgets.QLabel(self.centralwidget)
        self.computer_score_disply.setGeometry(QtCore.QRect(30, 130, 501, 51))
        self.computer_score_disply.setObjectName("computer_score")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
        method sets texts for buttons on GUI
        :param MainWindow:
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rock - Paper - Scissors"))
        self.Title.setText(_translate("MainWindow", "ROCK - PAPER - SCISSORS"))
        self.LowerTitleLine.setText(_translate("MainWindow", "---------------------------------"))
        self.UpperTitleLine.setText(_translate("MainWindow", "---------------------------------"))
        self.round_result.setText(_translate("MainWindow", ""))
        self.radioRock.setText(_translate("MainWindow", "rock"))
        self.radioPaper.setText(_translate("MainWindow", "paper"))
        self.radioScissors.setText(_translate("MainWindow", "scissors"))
        self.Choose.setText(_translate("MainWindow", "Choose"))
        self.Play_Again.setText(_translate("MainWindow", "Play game"))
        self.Quit.setText(_translate("MainWindow", "Quit"))
        self.choose_hand.setText(_translate("MainWindow", "Choose a hand:"))
        self.user_score_disply.setText(_translate("MainWindow", "Your score:           0"))
        self.computer_score_disply.setText(_translate("MainWindow", "Computer score:    0"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
